object Form1: TForm1
  Left = 0
  Top = 0
  VertScrollBar.Tracking = True
  Caption = 'Form1'
  ClientHeight = 647
  ClientWidth = 575
  Color = clBtnFace
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Segoe UI'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 8
    Top = 13
    Width = 64
    Height = 13
    Caption = 'V2 Costume:'
  end
  object Panel1: TPanel
    Left = 228
    Top = 0
    Width = 347
    Height = 647
    Align = alRight
    BevelOuter = bvNone
    FullRepaint = False
    ParentBackground = False
    TabOrder = 0
    object Panel2: TPanel
      Left = 0
      Top = 464
      Width = 347
      Height = 183
      Align = alBottom
      BevelOuter = bvNone
      TabOrder = 0
      ExplicitTop = 312
      ExplicitWidth = 316
      object Label4: TLabel
        Left = 9
        Top = 65
        Width = 56
        Height = 13
        Caption = 'Animation:'
      end
      object Label3: TLabel
        Left = 9
        Top = 5
        Width = 37
        Height = 13
        Caption = 'Facing:'
      end
      object Label2: TLabel
        Left = 9
        Top = 130
        Width = 34
        Height = 13
        Caption = 'Frame:'
      end
      object trkbrAnim: TTrackBar
        Left = 0
        Top = 89
        Width = 353
        Height = 29
        TabOrder = 0
      end
      object trkbrFacing: TTrackBar
        Left = 0
        Top = 24
        Width = 353
        Height = 31
        TabOrder = 1
      end
      object trkbrFrame: TTrackBar
        Left = 0
        Top = 149
        Width = 349
        Height = 28
        TabOrder = 2
      end
    end
    object ScrollBox1: TScrollBox
      Left = 0
      Top = 0
      Width = 347
      Height = 464
      VertScrollBar.Smooth = True
      VertScrollBar.Style = ssHotTrack
      VertScrollBar.Tracking = True
      Align = alClient
      BevelInner = bvNone
      BevelOuter = bvNone
      BorderStyle = bsNone
      TabOrder = 1
      ExplicitWidth = 330
      object Panel5: TPanel
        Left = 0
        Top = 4065
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 0
        object Label6: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '15:'
          ExplicitLeft = 9
          ExplicitTop = -3
        end
        object Image15: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel3: TPanel
        Left = 0
        Top = 271
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 1
        object Label5: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '1:'
        end
        object Image01: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel4: TPanel
        Left = 0
        Top = 0
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 2
        object Label7: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '0:'
        end
        object Image00: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel6: TPanel
        Left = 0
        Top = 3794
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 3
        object Label8: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '14:'
        end
        object Image14: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 24
        end
      end
      object Panel7: TPanel
        Left = 0
        Top = 3523
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 4
        object Label9: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '13:'
        end
        object Image13: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel8: TPanel
        Left = 0
        Top = 3252
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 5
        object Label10: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '12:'
        end
        object Image12: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel9: TPanel
        Left = 0
        Top = 2981
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 6
        object Label11: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '11:'
        end
        object Image11: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel10: TPanel
        Left = 0
        Top = 2710
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 7
        object Label12: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '10:'
        end
        object Image10: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel11: TPanel
        Left = 0
        Top = 2439
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 8
        object Label13: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '9:'
        end
        object Image09: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel12: TPanel
        Left = 0
        Top = 2168
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 9
        object Label14: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '8:'
        end
        object Image08: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel13: TPanel
        Left = 0
        Top = 1897
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 10
        object Label15: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '7:'
        end
        object Image07: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel14: TPanel
        Left = 0
        Top = 1626
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 11
        object Label16: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '6:'
        end
        object Image06: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel15: TPanel
        Left = 0
        Top = 1355
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 12
        object Label17: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '5:'
        end
        object Image05: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel16: TPanel
        Left = 0
        Top = 1084
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 13
        object Label18: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '4:'
        end
        object Image04: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel17: TPanel
        Left = 0
        Top = 813
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 14
        object Label19: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '3:'
        end
        object Image03: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
      object Panel18: TPanel
        Left = 0
        Top = 542
        Width = 330
        Height = 271
        Align = alTop
        BevelOuter = bvLowered
        Padding.Left = 4
        Padding.Top = 4
        Padding.Right = 4
        Padding.Bottom = 4
        TabOrder = 15
        object Label20: TLabel
          Left = 5
          Top = 5
          Width = 320
          Height = 21
          Align = alTop
          AutoSize = False
          Caption = '2:'
        end
        object Image02: TImage
          Left = 5
          Top = 26
          Width = 320
          Height = 240
          Margins.Left = 4
          Margins.Top = 8
          Margins.Right = 4
          Margins.Bottom = 4
          Align = alClient
          Transparent = True
          ExplicitTop = 13
        end
      end
    end
  end
  object Button1: TButton
    Left = 96
    Top = 8
    Width = 75
    Height = 25
    Caption = 'Open'
    TabOrder = 1
    OnClick = Button1Click
  end
  object OpenDialog1: TOpenDialog
    Left = 188
    Top = 4
  end
end
