unit SCUMMConsts;

interface

const
	VAL_SCUMMEXP_EXCORE_VMAJ = 0;
	VAL_SCUMMEXP_EXCORE_VMIN = 1;
	VAL_SCUMMEXP_EXCORE_VBLD = 0439;
	LIT_SCUMMEXP_EXCORE_VTYP = 'DEVELOPMENT';
	LIT_SCUMMEXP_EXCORE_VSTG = 'α';

	LIT_SCUMMEXP_EXCORE_VNAM = 'SCUMM Explorer';
	LIT_SCUMMEXP_EXCORE_VDSC = 'SCUMM Explorer Core.';

	LIT_SCUMMEXP_PATHDL_ROOT = '//';
	LIT_SCUMMEXP_PATHDL_NODE = '/';

	ARR_LIT_BOOL: array[Boolean] of string = ('false', 'true');
	ARR_LIT_TERM: array[Boolean] of string = ('/', '');

{$IFNDEF DEBUG}
	LIT_SCUMMEXP_KBPATH_LOCN = '.\kb';
{$ELSE}
	LIT_SCUMMEXP_KBPATH_LOCN = '..\..\..\kb';
{$ENDIF}
	LIT_SCUMMEXP_PLGPTH_LOCN = 'plugins';

	LIT_SCUMMEXP_PLGFNC_QUERY = 'SCUMMExpPlgQuery';
	LIT_SCUMMEXP_PLGFNC_INIT = 'SCUMMExpPlgInit';
	LIT_SCUMMEXP_PLGFNC_PREP = 'SCUMMExpPlgPrep';
	LIT_SCUMMEXP_PLGFNC_RELS = 'SCUMMExpPlgRels';
	LIT_SCUMMEXP_PLGFNC_FINL = 'SCUMMExpPlgFinl';

implementation

end.
