unit SPUTMDecV2Consts;

interface

const
	VAL_SCUMMEXP_DECDV2_VMAJ = 0;
	VAL_SCUMMEXP_DECDV2_VMIN = 1;
	VAL_SCUMMEXP_DECDV2_VBLD = 0435;
	LIT_SCUMMEXP_DECDV2_VTYP = 'DEVELOPMENT';
	LIT_SCUMMEXP_DECDV2_VSTG = 'α';
	LIT_SCUMMEXP_DECDV2_VNAM = 'SCUMM V2 Plugin';
	LIT_SCUMMEXP_DECDV2_VDSC = 'SCUMM Explorer V2 Plugin.';


implementation

end.
